version: "3.8"

networks:
  reverse-proxy-net:

services:
  pattern-lib:
    build:
      context: ./pattern-lib
      dockerfile: ./Dockerfile-node
    init: true
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./pattern-lib/env.template.yaml:/home/node/app/env.yaml:ro
      - ./pattern-lib/assets:/home/node/app/assets:ro
      - ./pattern-lib/bin:/home/node/app/bin:ro
      - ./pattern-lib/index.js:/home/node/app/index.js:ro
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - PORT=5000
    command: ["node", "./bin/pattern-lib.js"]
    networks:
      - reverse-proxy-net

  editorial-content:
    build:
      context: .
      dockerfile: Dockerfile-node
      args:
        - app=editorial-content
    init: true
    user: "node"
    volumes:
      - ./editorial-content/env.template.yaml:/home/node/app/env.yaml:ro
      - ./editorial-content/bin:/home/node/app/bin:ro
      - ./editorial-content/views:/home/node/app/views:ro
      - ./editorial-content/index.js:/home/node/app/index.js:ro
      - ./pattern-lib:/home/node/pattern-lib:ro # as install source for npm
    ports:
      - 5001:5001
    environment:
      - NODE_ENV=production
      - PORT=5001
    command: ["node", "./bin/editorial-content.js"]
    networks:
      - reverse-proxy-net

  products:
    build:
      context: .
      dockerfile: Dockerfile-node
      args:
        - app=products
    init: true
    user: "node"
    volumes:
      - ./products/env.template.yaml:/home/node/app/env.yaml:ro
      - ./products/bin:/home/node/app/bin:ro
      - ./products/data:/home/node/app/data:ro
      - ./products/views:/home/node/app/views:ro
      - ./products/index.js:/home/node/app/index.js:ro
      - ./pattern-lib:/home/node/pattern-lib:ro # as install source for npm
    ports:
      - 5002:5002
    environment:
      - NODE_ENV=production
      - PORT=5002
    command: ["node", "./bin/products.js"]
    networks:
      - reverse-proxy-net

  ordering:
    build:
      context: .
      dockerfile: Dockerfile-node
      args:
        - app=ordering
    init: true
    user: "node"
    volumes:
      - ./ordering/env.template.yaml:/home/node/app/env.yaml:ro
      - ./ordering/bin:/home/node/app/bin:ro
      - ./ordering/lib:/home/node/app/lib:ro
      - ./ordering/views:/home/node/app/views:ro
      - ./ordering/index.js:/home/node/app/index.js:ro
      - ./pattern-lib:/home/node/pattern-lib:ro # as install source for npm
    ports:
      - 5003:5003
    environment:
      - NODE_ENV=production
      - PORT=5003
    command: ["node", "./bin/ordering.js"]
    networks:
      - reverse-proxy-net

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:3000
    environment:
      - NGINX_PORT=3000
    networks:
      - reverse-proxy-net
