version: "3.8"

networks:
  reverse-proxy-net:

services:
  pattern-lib:
    image: node:latest
    init: true
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./pattern-lib:/home/node/app
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - PORT=5000
    command: npm start
    networks:
      - reverse-proxy-net

  editorial-content:
    image: node:latest
    init: true
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./editorial-content:/home/node/app
      - ./pattern-lib:/home/node/pattern-lib # as install source for npm
    ports:
      - 5001:5001
    environment:
      - NODE_ENV=production
      - PORT=5001
    command: npm start
    networks:
      - reverse-proxy-net

  products:
    image: node:latest
    init: true
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./products:/home/node/app
      - ./pattern-lib:/home/node/pattern-lib # as install source for npm
    ports:
      - 5002:5002
    environment:
      - NODE_ENV=production
      - PORT=5002
    command: npm start
    networks:
      - reverse-proxy-net

  ordering:
    image: node:latest
    init: true
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./ordering:/home/node/app
      - ./pattern-lib:/home/node/pattern-lib # as install source for npm
    ports:
      - 5003:5003
    environment:
      - NODE_ENV=production
      - PORT=5003
    command: npm start
    networks:
      - reverse-proxy-net

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:3000
    environment:
      - NGINX_PORT=3000
    networks:
      - reverse-proxy-net
